---
baseURL: "https://zenoh.io/"
relativeURLs: false
title: "Zenoh - The Zero Overhead, Pub/Sub, Store, Query, and Compute Protocol."
languageCode: "en-us"
canonifyURLs: false
markup:
  highlight:
    style: github
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNos: false
    tabWidth: 2

build:
  buildStats:
    enable: true
  writeStats: true
googleAnalytics: G-PBD6MS51QL
enableRobotsTXT: true
enableEmoji: true
singleViewStyle: "caspertwo"
ignoreLogs: ['warning-goldmark-raw-html']

params:
  description: "Eclipse Zenoh unifies pub/sub, query, storage, and computation across cloud, edge, robotics, IoT, and constrained devices."
  images:
    - "/img/zenoh-dragon-light.png"

sitemap:
    changefreq: "weekly"
    priority: 0.5

menu:
  docs:
    - identifier: "overview"
      name: "Overview"
      weight: 1000
    - identifier: "getting_started"
      name: "Getting started"
      weight: 2000
    - identifier: "manual"
      name: "Reference manual"
      weight: 3000
    - identifier: "APIs"
      name: "API"
      weight: 4000
    - identifier: "migration_1.0"
      name: "Migration guides v0.11 → v1.0"
      weight: 6000
    - identifier: "migration_1.9"
      name: "Migration guides v1.8 → v1.9"
      weight: 7000
